{% set name = "GTDBNCBI" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ecogenomics/{{ name }}/archive/{{ version }}.tar.gz
  sha256: fe251ce75dd30167f08dbc00e8c8a59cf6d788fa2b88647e9b5d9c739d197482

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=2.7,<3
    - pip
  run:
    - python >=2.7,<3
    - numpy
    - psycopg2
    - dendropy
    - biolib =0.0.52
    - prodigal =2.6.3
    - hmmer =3.1b2
    - fastani =1.1
    - fasttree =2.1.10
    - scipy =1.2.1
    - blast =2.9.0
    - pfam_search =0.1
    - genometk <0.1.0
    - prokka =1.13
    - trnascan-se =2.0
    - requests
    - unidecode
    - matplotlib-base
    - python-dateutil

test:
  imports:
    - gtdb

about:
  home: https://github.com/Ecogenomics/GTDBNCBI
