{% set name = "GTDBNCBI" %}
{% set version = "2.3.0" %}

package:
  name: "gtdb-r95"
  version: {{ version }}

source:
  url: https://github.com/Ecogenomics/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 5e184755a16593ccbed22a2d11bd7029b792495b2ab47dde70538a4e970d61b1

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=2.7,<3
    - pip
  run:
    - python >=2.7,<3
    - numpy
    - psycopg2
    - dendropy ==4.1.0
    - biolib ==0.0.52
    - prodigal ==2.6.3
    - hmmer ==3.1b2
    - fastani ==1.3
    - fasttree ==2.1.9
    - scipy ==0.17.1
    - blast ==2.9.0
    - pfam_search ==0.1
    - genometk

test:
  imports:
    - gtdb

about:
  home: https://github.com/Ecogenomics/GTDBNCBI
