{% set name = "GenomeTreeTk" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e88346f9d2c1d907b15a45f6213df22bef97cc184dd6522604e216299487c337

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - biolib >=0.1.0
    - numpy >=1.8.0
    - future
    - dendropy >=4.0.0

test:
  imports:
    - genometreetk
  commands:
    - genometreetk -h

about:
  home: https://github.com/dparks1134/GenomeTreeTk
  summary: 'The genome tree toolkit is a collection of methods for working with genome trees.'
