{% set name = "GTDBNCBI" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ecogenomics/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 044e7b0fff1ae45cd57a24d5725d31697c24250c51db5ca158e98df631b37679

build:
  noarch: python
  number: 1

requirements:
  host:
    - python >=2.7,<3
    - pip
  run:
    - python >=2.7,<3
    - numpy
    - psycopg2
    - dendropy
    - biolib =0.0.52
    - prodigal =2.6.3
    - hmmer =3.1b2
    - fastani =1.1
    - fasttree =2.1.10
    - scipy =1.2.1
    - blast =2.9.0
    - pfam_search =0.1
    - genometk <0.1.0
    - prokka =1.13
    - trnascan-se =2.0
    - requests
    - unidecode
    - matplotlib-base
    - python-dateutil

test:
  imports:
    - gtdb

about:
  home: https://github.com/Ecogenomics/GTDBNCBI
