{% set name = "biolib" %}
{% set version = "0.0.52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6f6d82a52426ffa9ef454d034b192b60281e235d3c15b7a11af3574fee2a8597

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=2.7,<3
    - pip
  run:
    - python >=2.7,<3

test:
  imports:
    - biolib
    - biolib.misc
    - biolib.external
    - biolib.plots

about:
  home: https://github.com/dparks1134/biolib