{% set name = "GenomeTk" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54b217a32d8581344fcdc0f6272a03865f6e4d399ba53394dc7f23b6b6330c27

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=2.7,<3
    - pip
  run:
    - python >=2.7,<3
    - biolib >=0.0.11
    - numpy >=1.8.0
    - future
    - dendropy

test:
  imports:
    - genometk
  commands:
    - genometk -h

about:
  home: https://github.com/dparks1134/GenomeTk
  summary: 'The genome toolkit is a collection of methods for determining characteristics about genomes.'
