{% set name = "GenomeTreeTk" %}
{% set version = "0.0.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2947db56a1b8e9fd9e8d7f1f73fa75d1af67ee44ff8a058a18c70dc544d36b6b

build:
  noarch: python
  number: 2

requirements:
  host:
    - python >=2.7,<3
    - pip
  run:
    - python >=2.7,<3
    - biolib >=0.0.45,<0.1.0
    - numpy >=1.8.0
    - future
    - dendropy >=4.0.0
    - fasttree
    - blast
    - hmmer ==3.1b2
    - biolib <0.1.0
    - scipy >=0.16.0
    - infernal
    - fastani >=1.3
    - mash
    - mothur
    - ssu-align
    - easel

test:
  imports:
    - genometreetk
  commands:
    - genometreetk -h

about:
  home: https://github.com/dparks1134/GenomeTreeTk
  summary: 'The genome tree toolkit is a collection of methods for working with genome trees.'
