{% set name = "biolib" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ef71237c8f3a35027ddc00a7e924e520f147d37783ab1a211b0e2aae685dcef

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - biolib
    - biolib.misc
    - biolib.external
    - biolib.plots

about:
  home: https://github.com/dparks1134/biolib